"use client";

import { FormEvent, useEffect, useState } from "react";

type Partner={
  id:string;name:string;slug:string;contact_name:string|null;contact_email:string|null;status:string;
  reward_mode:string;reward_basis:string;partner_reward_cents:number;partner_reward_percent:number;
  guest_discount_cents:number;guest_discount_percent:number;promo_code:string|null;attribution_window_days:number;
  show_promo_popup:boolean;popup_heading:string|null;popup_body:string|null;
};

const field:React.CSSProperties={width:"100%",height:44,border:"1px solid #cfd6de",borderRadius:10,padding:"0 11px",boxSizing:"border-box",background:"white"};
const label:React.CSSProperties={display:"grid",gap:6,fontSize:12,fontWeight:800,color:"#39414b"};
const card:React.CSSProperties={background:"rgba(255,255,255,.97)",border:"1px solid #dfe4ea",borderRadius:18,boxShadow:"0 14px 34px rgba(26,35,48,.07)"};

export default function EditAmbassadorPage({params}:{params:Promise<{partnerId:string}>}){
  const [partnerId,setPartnerId]=useState("");const [p,setP]=useState<Partner|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const [name,setName]=useState("");const [slug,setSlug]=useState("");const [contactName,setContactName]=useState("");const [contactEmail,setContactEmail]=useState("");const [status,setStatus]=useState("active");const [mode,setMode]=useState("partner_reward");const [basis,setBasis]=useState("flat");const [partnerReward,setPartnerReward]=useState("0");const [guestDiscount,setGuestDiscount]=useState("0");const [promo,setPromo]=useState("");const [windowDays,setWindowDays]=useState("30");const [popup,setPopup]=useState(false);const [popupHeading,setPopupHeading]=useState("");const [popupBody,setPopupBody]=useState("");

  useEffect(()=>{params.then(x=>setPartnerId(x.partnerId));},[params]);
  useEffect(()=>{if(!partnerId)return;fetch("/api/ambassador/admin/partner-management",{cache:"no-store"}).then(async r=>{if(r.status===401||r.status===403){window.location.href="/ambassador/admin/login";return;}const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to load Ambassador.");const partner=(data.partners||[]).find((x:Partner)=>x.id===partnerId);if(!partner)throw new Error("Ambassador not found.");setP(partner);setName(partner.name);setSlug(partner.slug);setContactName(partner.contact_name||"");setContactEmail(partner.contact_email||"");setStatus(partner.status||"active");setMode(partner.reward_mode||"partner_reward");setBasis(partner.reward_basis||"flat");setPartnerReward(partner.reward_basis==="percent"?String(partner.partner_reward_percent||0):String((partner.partner_reward_cents||0)/100));setGuestDiscount(partner.reward_basis==="percent"?String(partner.guest_discount_percent||0):String((partner.guest_discount_cents||0)/100));setPromo(partner.promo_code||"");setWindowDays(String(partner.attribution_window_days||30));setPopup(Boolean(partner.show_promo_popup));setPopupHeading(partner.popup_heading||"");setPopupBody(partner.popup_body||"");}).catch(e=>setError(e instanceof Error?e.message:"Unable to load Ambassador."));},[partnerId]);

  async function save(e:FormEvent){e.preventDefault();if(!p)return;setBusy(true);setError("");setMessage("");try{const pv=Number(partnerReward)||0,gv=Number(guestDiscount)||0;const r=await fetch("/api/ambassador/admin/partner-management",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,name,slug,contact_name:contactName,contact_email:contactEmail,status,reward_mode:mode,reward_basis:basis,partner_reward_cents:basis==="flat"?Math.round(pv*100):0,partner_reward_percent:basis==="percent"?pv:0,guest_discount_cents:basis==="flat"?Math.round(gv*100):0,guest_discount_percent:basis==="percent"?gv:0,promo_code:promo,attribution_window_days:Number(windowDays)||30,show_promo_popup:popup,popup_heading:popupHeading,popup_body:popupBody})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Unable to update Ambassador.");setMessage("Ambassador updated. New referral bookings will use these rules; existing bookings remain locked to their original terms.");}catch(err){setError(err instanceof Error?err.message:"Unable to update Ambassador.");}finally{setBusy(false);}}

  if(!p)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#eef2f5",fontFamily:"Arial,sans-serif",color:"#68717d"}}>{error||"Loading Ambassador…"}</main>;

  const rewardUnit=basis==="percent"?"%":"$";
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 85% 0%,rgba(213,82,29,.10),transparent 28%),linear-gradient(180deg,#f5f7f9 0%,#edf1f4 100%)",fontFamily:"Arial,sans-serif",color:"#202733"}}>
    <div style={{padding:28,maxWidth:1180,margin:"0 auto"}}>
      <div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:20}}><div><div style={{fontSize:11,fontWeight:900,color:"#d5521d",textTransform:"uppercase",letterSpacing:1}}>Partner Management</div><h1 style={{margin:"5px 0 0",fontSize:32}}>Edit {p.name}</h1><p style={{margin:"7px 0 0",color:"#68717d"}}>Changes apply to future referrals. Existing attributed bookings keep the reward terms they were booked under.</p></div><button onClick={()=>window.location.href="/ambassador/admin"} style={{border:"1px solid #cfd6de",background:"white",borderRadius:10,padding:"10px 14px",fontWeight:800,cursor:"pointer"}}>Back to Ambassador</button></div>
      <form onSubmit={save} style={{...card,padding:24,display:"grid",gap:18}}>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14}}><label style={label}>Partner Name<input style={field} value={name} onChange={e=>setName(e.target.value)} required/></label><label style={label}>Referral Code<input style={field} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())} required/></label><label style={label}>Contact Name<input style={field} value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label style={label}>Contact Email<input style={field} type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(0,1fr))",gap:14}}><label style={label}>Reward Arrangement<select style={field} value={mode} onChange={e=>setMode(e.target.value)}><option value="partner_reward">Partner Reward</option><option value="guest_discount">Guest Discount</option><option value="split">Split Reward</option></select></label><label style={label}>Calculation<select style={field} value={basis} onChange={e=>setBasis(e.target.value)}><option value="flat">Flat Amount</option><option value="percent">Percentage</option></select></label><label style={label}>Partner Reward ({rewardUnit})<input style={field} type="number" step="0.01" min="0" value={partnerReward} onChange={e=>setPartnerReward(e.target.value)}/></label><label style={label}>Guest Discount ({rewardUnit})<input style={field} type="number" step="0.01" min="0" value={guestDiscount} onChange={e=>setGuestDiscount(e.target.value)}/></label><label style={label}>Attribution Days<input style={field} type="number" min="1" max="365" value={windowDays} onChange={e=>setWindowDays(e.target.value)}/></label><label style={label}>Status<select style={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><label style={label}>TripWorks Promo Code<input style={field} value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/></label><label style={{...label,alignContent:"end"}}><span>Guest Promo Popup</span><span style={{height:44,display:"flex",alignItems:"center",gap:9,border:"1px solid #cfd6de",borderRadius:10,padding:"0 12px",background:"white",fontWeight:700}}><input type="checkbox" checked={popup} onChange={e=>setPopup(e.target.checked)}/> Show popup to referred guests</span></label></div>
        {popup?<div style={{display:"grid",gridTemplateColumns:"1fr 1.5fr",gap:14}}><label style={label}>Popup Heading<input style={field} value={popupHeading} onChange={e=>setPopupHeading(e.target.value)} placeholder={`A special offer from ${name}`}/></label><label style={label}>Popup Message<input style={field} value={popupBody} onChange={e=>setPopupBody(e.target.value)} placeholder="Leave blank to use the automatic discount message"/></label></div>:null}
        <div style={{padding:14,borderRadius:12,background:"#fff7f2",border:"1px solid #f2cbb8",fontSize:13,lineHeight:1.5,color:"#7a421d"}}><strong>Historical protection:</strong> editing these reward settings does not recalculate old referrals upward. Existing bookings stay locked to the terms captured when they were attributed; only legitimate booking-value reductions can reduce an unpaid commission.</div>
        {error?<div style={{color:"#b42318",fontWeight:800}}>{error}</div>:null}{message?<div style={{color:"#18794e",fontWeight:800}}>{message}</div>:null}
        <div style={{display:"flex",gap:10}}><button disabled={busy} type="submit" style={{border:0,borderRadius:10,background:"linear-gradient(135deg,#df5b22,#c94716)",color:"white",padding:"12px 19px",fontWeight:900,cursor:busy?"wait":"pointer",boxShadow:"0 10px 22px rgba(213,82,29,.20)"}}>{busy?"Saving…":"Save Ambassador"}</button><button type="button" onClick={()=>window.location.href="/ambassador/admin"} style={{border:"1px solid #cfd6de",background:"white",borderRadius:10,padding:"12px 17px",fontWeight:800,cursor:"pointer"}}>Cancel</button></div>
      </form>
    </div>
  </main>;
}
