"use client";

import { useEffect, useState } from "react";

type Row = { id:string; amount_cents:number; method:string; method_details:Record<string,unknown>; status:string; requested_at:string; provider?:string|null; provider_reference?:string|null; internal_notes?:string|null; partner?:{name:string}|null };
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
const date=(v:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v));
const title=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());

export default function RedemptionRequestsClient(){
  const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
  async function load(){ const r=await fetch("/api/team/referral-redemptions",{cache:"no-store"}); const p=await r.json(); if(!r.ok) throw new Error(p.error||"Unable to load redemptions."); setRows(p.redemptions||[]); }
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Unable to load redemptions."));},[]);
  async function update(row:Row,status:string){ setBusy(row.id+status); setError(""); try{ const r=await fetch("/api/team/referral-redemptions",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,status})}); const p=await r.json(); if(!r.ok) throw new Error(p.error||"Unable to update redemption."); await load(); }catch(e){setError(e instanceof Error?e.message:"Unable to update redemption.");}finally{setBusy("");}}
  const detail=(row:Row)=>{ const d=row.method_details||{}; if(row.method==="gift_card") return String(d.brand||""); if(row.method==="venmo") return String(d.handle||""); if(row.method==="paypal") return String(d.email||""); if(row.method==="check") return `${String(d.payee||"")} · ${String(d.address||"")}`; return ""; };
  return <section style={{background:"white",border:"1px solid #dfe4ea",borderRadius:16,overflow:"hidden"}}>
    <div style={{padding:"20px 22px",borderBottom:"1px solid #e5e9ee",display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"}}><div><h2 style={{margin:0,fontSize:21}}>Redemption Requests</h2><p style={{margin:"5px 0 0",color:"#7b8491",fontSize:14}}>Approve and fulfill Ambassador reward requests.</p></div><div style={{fontWeight:800}}>{rows.filter(r=>r.status==="requested").length} pending</div></div>
    {error?<div style={{padding:18,color:"#b42318"}}>{error}</div>:null}
    <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr style={{background:"#f8f9fa",textAlign:"left"}}>{["Partner","Requested","Amount","Method","Destination","Status","Actions"].map(h=><th key={h} style={{padding:"11px 14px",color:"#68717d"}}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id} style={{borderTop:"1px solid #eef1f4"}}><td style={{padding:"12px 14px",fontWeight:800}}>{row.partner?.name||"Partner"}</td><td style={{padding:"12px 14px"}}>{date(row.requested_at)}</td><td style={{padding:"12px 14px",fontWeight:800}}>{money(row.amount_cents)}</td><td style={{padding:"12px 14px"}}>{title(row.method)}</td><td style={{padding:"12px 14px",maxWidth:320,whiteSpace:"pre-wrap"}}>{detail(row)}</td><td style={{padding:"12px 14px"}}>{title(row.status)}</td><td style={{padding:"12px 14px"}}><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{row.status==="requested"&&<><button disabled={!!busy} onClick={()=>update(row,"approved")} style={{padding:"7px 10px",border:0,borderRadius:7,background:"#202733",color:"white",fontWeight:700}}>Approve</button><button disabled={!!busy} onClick={()=>update(row,"rejected")} style={{padding:"7px 10px",border:"1px solid #d7dde5",borderRadius:7,background:"white",fontWeight:700}}>Reject</button></>}{row.status==="approved"&&<button disabled={!!busy} onClick={()=>update(row,"sent")} style={{padding:"7px 10px",border:0,borderRadius:7,background:"#d5521d",color:"white",fontWeight:700}}>Mark Sent</button>}{row.status==="sent"&&<button disabled={!!busy} onClick={()=>update(row,"completed")} style={{padding:"7px 10px",border:0,borderRadius:7,background:"#18794e",color:"white",fontWeight:700}}>Complete</button>}{!["completed","rejected","cancelled"].includes(row.status)&&<button disabled={!!busy} onClick={()=>update(row,"cancelled")} style={{padding:"7px 10px",border:"1px solid #d7dde5",borderRadius:7,background:"white",fontWeight:700}}>Cancel</button>}</div></td></tr>):<tr><td colSpan={7} style={{padding:28,textAlign:"center",color:"#68717d"}}>No redemption requests yet.</td></tr>}</tbody></table></div>
  </section>;
}
