import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedAmbassadorAdmin } from "@/lib/ambassador-admin-auth";

function cfg(){const raw=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();const key=process.env.SUPABASE_SECRET_KEY?.trim();if(!raw||!key)throw new Error("Supabase server environment variables are missing.");return{url:(/^https?:\/\//i.test(raw)?raw:`https://${raw}`).replace(/\/+$/,"") ,key};}
async function rest<T>(path:string,init?:RequestInit):Promise<T>{const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(text||`Supabase request failed (${r.status}).`);return text?JSON.parse(text) as T:undefined as T;}
async function admin(req:NextRequest){return getAuthenticatedAmbassadorAdmin(req.cookies.get("epic_ambassador_admin_access_token")?.value);}

export async function GET(req:NextRequest){if(!await admin(req))return NextResponse.json({error:"Ambassador administrator access required."},{status:403});const partnerId=req.nextUrl.searchParams.get("partner_id")?.trim()||"";try{const path=partnerId?`referral_partner_profiles?partner_id=eq.${encodeURIComponent(partnerId)}&select=id,partner_id,user_id,display_name,email,role,active,invited_at,last_login_at,updated_at&order=display_name.asc`:`referral_partner_profiles?select=id,partner_id,user_id,display_name,email,role,active,invited_at,last_login_at,updated_at&order=display_name.asc`;const users=await rest<any[]>(path);return NextResponse.json({ok:true,users});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load portal users."},{status:500});}}

export async function POST(req:NextRequest){if(!await admin(req))return NextResponse.json({error:"Ambassador administrator access required."},{status:403});const body=await req.json().catch(()=>null) as Record<string,unknown>|null;const partnerId=typeof body?.partner_id==="string"?body.partner_id.trim():"";const displayName=typeof body?.display_name==="string"?body.display_name.trim():"";const email=typeof body?.email==="string"?body.email.trim().toLowerCase():"";const role=body?.role==="owner"||body?.role==="viewer"?body.role:"manager";if(!partnerId||!displayName||!email.includes("@"))return NextResponse.json({error:"Partner, name, and a valid email are required."},{status:400});try{const partner=await rest<any[]>(`referral_partners?id=eq.${encodeURIComponent(partnerId)}&select=id,name&limit=1`);if(!partner[0])return NextResponse.json({error:"Ambassador not found."},{status:404});const existing=await rest<any[]>(`referral_partner_profiles?partner_id=eq.${encodeURIComponent(partnerId)}&email=ilike.${encodeURIComponent(email)}&select=id,active&limit=1`);if(existing[0])return NextResponse.json({error:existing[0].active?"That email already has access to this Ambassador.":"That email already exists but is revoked. Reactivate it instead."},{status:409});const profiles=await rest<any[]>("referral_partner_profiles",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({partner_id:partnerId,display_name:displayName,email,role,active:true,invited_at:new Date().toISOString()})});const{url,key}=cfg();const redirectTo="https://www.epic4x4ambassador.com/ambassador/setup";const r=await fetch(`${url}/auth/v1/invite?redirect_to=${encodeURIComponent(redirectTo)}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({email,data:{account_type:"ambassador",display_name:displayName,ambassador_profile_id:profiles[0].id,partner_id:partnerId,partner_name:partner[0].name,role}}),cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok){await rest<void>(`referral_partner_profiles?id=eq.${encodeURIComponent(profiles[0].id)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});throw new Error(p?.msg||p?.message||p?.error_description||"Unable to send Ambassador invitation.");}return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to invite portal user."},{status:500});}}

export async function PATCH(req:NextRequest){if(!await admin(req))return NextResponse.json({error:"Ambassador administrator access required."},{status:403});const body=await req.json().catch(()=>null) as Record<string,unknown>|null;const id=typeof body?.profile_id==="string"?body.profile_id.trim():"";const active=typeof body?.active==="boolean"?body.active:null;if(!id||active===null)return NextResponse.json({error:"Profile and access status are required."},{status:400});try{const rows=await rest<any[]>(`referral_partner_profiles?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({active,updated_at:new Date().toISOString()})});if(!rows[0])return NextResponse.json({error:"Portal user not found."},{status:404});return NextResponse.json({ok:true,user:rows[0]});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update portal access."},{status:500});}}
