"use client";

import { useEffect, useMemo, useState } from "react";

type WorkItem = {
  id:string; source_record_id:string|null; work_type:string; status:string; subject:string|null; summary:string|null;
  assigned_profile_id:string|null; assigned_name:string|null; created_at:string; metadata:Record<string,unknown>;
};
function text(v:unknown){return typeof v==="string"?v:v==null?"":String(v)}
function timeLabel(value:string){return new Intl.DateTimeFormat("en-US",{timeZone:"America/Denver",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value))}
function phoneHref(v:unknown){const digits=text(v).replace(/\D/g,"");return digits?`tel:+${digits.length===10?`1${digits}`:digits}`:"#"}

export default function MissedCallsTable({initialItems}:{initialItems:WorkItem[]}){
  const [items,setItems]=useState(initialItems); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState("");
  const unclaimed=useMemo(()=>items.filter(i=>!i.assigned_name).length,[items]);
  async function refresh(){try{const r=await fetch("/api/team/leads/inbox",{cache:"no-store"});const p=await r.json();if(r.ok){setItems((p.items||[]).filter((i:WorkItem)=>{const m=i.metadata||{};return text(m.channel)==="call"&&((m.answered===false)||["missed","abandoned"].includes(text(m.call_type).toLowerCase()))}))}}catch{}}
  useEffect(()=>{const t=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh()},5000);return()=>window.clearInterval(t)},[]);
  async function inboxAction(item:WorkItem,action:string,workType?:string){setBusy(item.id);setError("");try{const r=await fetch("/api/team/leads/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,work_item_id:item.id,work_type:workType})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to update call.");await refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update call.")}finally{setBusy(null)}}
  async function createLead(item:WorkItem){setBusy(item.id);setError("");try{const r=await fetch("/api/team/leads/missed-calls/prepare-lead",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({work_item_id:item.id})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to prepare lead.");window.location.href=`/team/leads/live-call?live_call=${encodeURIComponent(p.live_call_id)}`}catch(e){setError(e instanceof Error?e.message:"Unable to prepare lead.")}finally{setBusy(null)}}
  return <>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14,gap:12}}><div style={{color:"#6e7986",fontWeight:750}}>{items.length} callback{items.length===1?"":"s"} · {unclaimed} unclaimed</div><button onClick={()=>void refresh()} style={{border:"1px solid #d6dde5",background:"white",borderRadius:9,padding:"9px 13px",fontWeight:850,cursor:"pointer"}}>Refresh</button></div>
    {error?<div style={{marginBottom:12,padding:12,borderRadius:10,background:"#fff1ef",border:"1px solid #efb9b2",color:"#97372f",fontWeight:800}}>{error}</div>:null}
    <div style={{display:"grid",gap:12}}>{items.map(item=>{const m=item.metadata||{};const phone=text(m.phone);const caller=text(m.caller_name)||phone||"Unknown caller";return <article key={item.id} style={{border:"1px solid #e7b0aa",borderRadius:14,background:"#fff8f7",padding:16,display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:14}}>
      <div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{fontSize:18}}>{caller}</strong><span style={{fontSize:11,fontWeight:900,textTransform:"uppercase",letterSpacing:".08em",padding:"4px 7px",borderRadius:999,background:"#ffe0dc",color:"#a3392d"}}>{text(m.call_type)||"missed"}</span></div><div style={{fontWeight:850,marginTop:6}}>{phone}</div><div style={{color:"#687585",marginTop:5}}>{item.summary||"Unanswered inbound call"}</div><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:9,fontSize:13,color:"#6f7c89",fontWeight:750}}><span>{timeLabel(item.created_at)}</span>{text(m.source_name)?<span>{text(m.source_name)}</span>:null}{text(m.campaign)?<span>{text(m.campaign)}</span>:null}{text(m.recording_url)?<a href={text(m.recording_url)} target="_blank" rel="noreferrer">Listen ↗</a>:null}</div></div>
      <div style={{display:"grid",gap:8,minWidth:200}}><strong>{item.assigned_name||"Unclaimed"}</strong>{!item.assigned_name?<button disabled={busy===item.id} onClick={()=>void inboxAction(item,"claim")} style={{border:0,borderRadius:9,padding:"9px 12px",background:"#202936",color:"white",fontWeight:900}}>Claim</button>:<button disabled={busy===item.id} onClick={()=>void inboxAction(item,"release")} style={{border:"1px solid #d4dce3",borderRadius:9,padding:"9px 12px",background:"white",fontWeight:850}}>Release</button>}<a href={phoneHref(phone)} style={{textAlign:"center",textDecoration:"none",border:"1px solid #c9d3dc",borderRadius:9,padding:"9px 12px",background:"white",fontWeight:900,color:"#202936"}}>Call Back</a><button disabled={busy===item.id} onClick={()=>void createLead(item)} style={{border:0,borderRadius:9,padding:"9px 12px",background:"#b42318",color:"white",fontWeight:900}}>Create Lead</button><button disabled={busy===item.id} onClick={()=>void inboxAction(item,"classify","other")} style={{border:"1px solid #d4dce3",borderRadius:9,padding:"8px 10px",background:"white",fontWeight:800}}>Other / Internal</button><button disabled={busy===item.id} onClick={()=>void inboxAction(item,"classify","junk")} style={{border:"1px solid #d4dce3",borderRadius:9,padding:"8px 10px",background:"white",fontWeight:800}}>Junk</button></div>
    </article>})}{!items.length?<div style={{padding:24,textAlign:"center",color:"#778391",border:"1px dashed #cfd7df",borderRadius:14}}>No missed or abandoned calls waiting for callback.</div>:null}</div>
  </>
}
