"use client";

import { FormEvent, useEffect, useState } from "react";

type Reward={id:string;slug:string;category:string;display_name:string;image_status:"placeholder"|"ready";image_url:string|null;redemption_type:string;amount_type:"fixed"|"custom";allowed_amounts_cents:number[];min_amount_cents:number;max_amount_cents:number|null;fee_cents:number;fee_note:string|null;active:boolean;sort_order:number};
const field:React.CSSProperties={width:"100%",height:42,border:"1px solid #cfd5dc",borderRadius:10,padding:"0 11px",boxSizing:"border-box",background:"white"};
const label:React.CSSProperties={display:"grid",gap:6,fontSize:12,fontWeight:800,color:"#39414b"};
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
const categories=["Moab & Local","Moab Dining","Outdoor & Local Retail","Travel & Lodging","National Brands","Cash & Digital","Open Loop Cards"];
const blank={slug:"",category:"Moab & Local",display_name:"",image_status:"placeholder",image_url:"",redemption_type:"gift_card",amount_type:"fixed",denominations:"25,50,100",min_amount:"10",max_amount:"",fee:"0",fee_note:"",active:true,sort_order:"100"};
const card:React.CSSProperties={background:"rgba(255,255,255,.97)",border:"1px solid #dfe4ea",borderRadius:18,boxShadow:"0 14px 34px rgba(26,35,48,.07)"};
function titleCase(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());}

export default function AmbassadorAdminRewardsPage(){
  const [rows,setRows]=useState<Reward[]>([]); const [form,setForm]=useState(blank); const [editingId,setEditingId]=useState(""); const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){const r=await fetch("/api/ambassador/admin/reward-catalog",{cache:"no-store"});if(r.status===401||r.status===403){window.location.href="/ambassador/admin/login";return;}const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load reward catalog.");setRows(p.rewards||[]);}
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Unable to load reward catalog."));},[]);
  function change(name:string,value:any){setForm(f=>({...f,[name]:value}));}
  function reset(){setForm(blank);setEditingId("");setError("");setMessage("");}
  function edit(row:Reward){setEditingId(row.id);setForm({slug:row.slug,category:row.category,display_name:row.display_name,image_status:row.image_status,image_url:row.image_url||"",redemption_type:row.redemption_type,amount_type:row.amount_type,denominations:(row.allowed_amounts_cents||[]).map(v=>String(v/100)).join(","),min_amount:String((row.min_amount_cents||0)/100),max_amount:row.max_amount_cents?String(row.max_amount_cents/100):"",fee:String((row.fee_cents||0)/100),fee_note:row.fee_note||"",active:row.active,sort_order:String(row.sort_order||100)});window.scrollTo({top:0,behavior:"smooth"});}
  async function uploadImage(file:File){setUploading(true);setError("");setMessage("");try{const fd=new FormData();fd.append("file",file);fd.append("slug",form.slug||form.display_name||"reward");const r=await fetch("/api/ambassador/admin/reward-image",{method:"POST",body:fd});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to upload image.");setForm(f=>({...f,image_url:p.image_url,image_status:"ready"}));setMessage("Image uploaded. Save the reward to apply it.");}catch(e){setError(e instanceof Error?e.message:"Unable to upload image.");}finally{setUploading(false);}}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const denominations=form.denominations.split(",").map(v=>Math.round(Number(v.trim())*100)).filter(v=>Number.isFinite(v)&&v>0);const payload={id:editingId||undefined,slug:form.slug,category:form.category,display_name:form.display_name,image_status:form.image_url?"ready":form.image_status,image_url:form.image_url,redemption_type:form.redemption_type,amount_type:form.amount_type,allowed_amounts_cents:denominations,min_amount_cents:Math.round(Number(form.min_amount||0)*100),max_amount_cents:form.max_amount?Math.round(Number(form.max_amount)*100):null,fee_cents:Math.round(Number(form.fee||0)*100),fee_note:form.fee_note,active:form.active,sort_order:Number(form.sort_order)||100};const r=await fetch("/api/ambassador/admin/reward-catalog",{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to save reward.");setMessage(editingId?"Reward updated.":"Reward added.");setForm(blank);setEditingId("");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save reward.");}finally{setBusy(false);}}
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 85% 0%,rgba(213,82,29,.10),transparent 28%),linear-gradient(180deg,#f5f7f9 0%,#edf1f4 100%)",color:"#202733",fontFamily:"Arial,sans-serif"}}>
    <header style={{position:"relative",overflow:"hidden",background:"linear-gradient(135deg,#1e2a39 0%,#182230 55%,#111821 100%)",color:"white",padding:"18px 28px",boxShadow:"0 12px 30px rgba(16,24,33,.18)"}}><div style={{position:"absolute",inset:0,opacity:.1,backgroundImage:"radial-gradient(circle at 20% 20%,#fff 1px,transparent 1px)",backgroundSize:"24px 24px"}}/><div style={{position:"relative",display:"flex",alignItems:"center",gap:18}}><img src="/epic-logo.png" alt="Epic 4X4" style={{width:132,filter:"brightness(0) invert(1)"}}/><div><div style={{fontSize:24,fontWeight:900}}>Rewards Catalog</div><div style={{fontSize:13,opacity:.72}}>Ambassador Administration · Epic 4X4 Adventures</div></div></div></header>
    <div style={{padding:28}}><section style={{...card,padding:24}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",marginBottom:20}}><div><div style={{fontSize:11,fontWeight:900,color:"#d5521d",textTransform:"uppercase",letterSpacing:1}}>Prize Management</div><h1 style={{margin:"4px 0 0",fontSize:30}}>Manage Rewards</h1><p style={{margin:"7px 0 0",color:"#68717d",fontSize:13}}>Add, edit, deactivate, reorder, price, and upload artwork for the rewards Ambassadors can choose.</p></div><div style={{background:"#fff1ea",color:"#d5521d",border:"1px solid #f3c2aa",borderRadius:12,padding:"10px 13px",fontSize:12,fontWeight:900}}>{rows.filter(r=>r.active).length} Active Rewards</div></div>
      <form onSubmit={save} style={{display:"grid",gap:15,background:"linear-gradient(145deg,#fbfcfd,#f6f8fa)",border:"1px solid #e5e9ee",borderRadius:14,padding:18}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:34,height:34,borderRadius:10,display:"grid",placeItems:"center",background:"#fff1ea",color:"#d5521d",fontWeight:900}}>{editingId?"✎":"+"}</div><div><strong style={{fontSize:16}}>{editingId?"Edit Reward":"Add New Reward"}</strong><div style={{fontSize:12,color:"#68717d",marginTop:2}}>Manage card details, artwork, denominations, and fee rules.</div></div></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1.3fr 1fr 1fr",gap:12}}><label style={label}>Category<select style={field} value={form.category} onChange={e=>change("category",e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label style={label}>Display Name<input style={field} value={form.display_name} onChange={e=>change("display_name",e.target.value)} required/></label><label style={label}>Reward Code<input style={field} value={form.slug} onChange={e=>change("slug",e.target.value)} placeholder="gearheads" required/></label><label style={label}>Image Status<input style={{...field,background:"#f7f8fa"}} value={form.image_url?"Ready":"Placeholder"} readOnly/></label></div>
        <div style={{display:"grid",gridTemplateColumns:"minmax(360px,1.5fr) 1fr 1fr 1fr",gap:12,alignItems:"end"}}><label style={label}>Reward Image<div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input style={field} value={form.image_url} onChange={e=>change("image_url",e.target.value)} placeholder="Upload an image or paste a URL"/><label style={{height:42,display:"inline-flex",alignItems:"center",justifyContent:"center",borderRadius:10,background:"#202733",color:"white",fontWeight:900,padding:"0 14px",cursor:uploading?"wait":"pointer",whiteSpace:"nowrap"}}>{uploading?"Uploading…":"Upload Image"}<input type="file" accept="image/jpeg,image/png,image/webp" hidden disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadImage(f);e.currentTarget.value="";}}/></label></div>{form.image_url?<div style={{marginTop:7,display:"flex",alignItems:"center",gap:10}}><img src={form.image_url} alt="Reward preview" style={{width:92,height:56,objectFit:"cover",borderRadius:8,border:"1px solid #dfe4ea"}}/><span style={{fontSize:11,color:"#18794e",fontWeight:800}}>Artwork ready</span></div>:<div style={{fontSize:11,color:"#68717d",marginTop:5}}>JPG, PNG, or WebP · up to 5 MB</div>}</label><label style={label}>Redemption Type<select style={field} value={form.redemption_type} onChange={e=>change("redemption_type",e.target.value)}><option value="gift_card">Gift Card</option><option value="prepaid_card">Prepaid Card</option><option value="venmo">Venmo</option><option value="paypal">PayPal</option><option value="check">Mailed Check</option></select></label><label style={label}>Amount Type<select style={field} value={form.amount_type} onChange={e=>change("amount_type",e.target.value)}><option value="fixed">Fixed Denominations</option><option value="custom">Custom Amount</option></select></label><label style={label}>Sort Order<input style={field} type="number" value={form.sort_order} onChange={e=>change("sort_order",e.target.value)}/></label></div>
        {form.amount_type==="fixed"?<label style={label}>Allowed Amounts (dollars, comma separated)<input style={field} value={form.denominations} onChange={e=>change("denominations",e.target.value)} placeholder="10,25,50,100"/></label>:<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><label style={label}>Minimum Amount ($)<input style={field} type="number" min="0" step="1" value={form.min_amount} onChange={e=>change("min_amount",e.target.value)}/></label><label style={label}>Maximum Amount ($, optional)<input style={field} type="number" min="0" step="1" value={form.max_amount} onChange={e=>change("max_amount",e.target.value)}/></label></div>}
        <div style={{display:"grid",gridTemplateColumns:"180px 1fr 180px",gap:12}}><label style={label}>Fee ($)<input style={field} type="number" min="0" step="0.01" value={form.fee} onChange={e=>change("fee",e.target.value)}/></label><label style={label}>Fee Note<input style={field} value={form.fee_note} onChange={e=>change("fee_note",e.target.value)} placeholder="Fees apply and are deducted from redeemable rewards balance."/></label><label style={{...label,alignContent:"end"}}><span>Availability</span><span style={{height:42,display:"flex",alignItems:"center",gap:8,background:"white",border:"1px solid #cfd5dc",borderRadius:10,padding:"0 11px"}}><input type="checkbox" checked={form.active} onChange={e=>change("active",e.target.checked)}/> Active</span></label></div>
        <div style={{display:"flex",gap:10}}><button disabled={busy||uploading} style={{border:0,borderRadius:10,background:"linear-gradient(135deg,#df5b22,#c94716)",color:"white",padding:"11px 17px",fontWeight:900,boxShadow:"0 9px 20px rgba(213,82,29,.18)"}}>{busy?"Saving…":editingId?"Save Changes":"Add Reward"}</button>{editingId?<button type="button" onClick={reset} style={{border:"1px solid #cfd5dc",borderRadius:10,background:"white",padding:"11px 17px",fontWeight:800}}>Cancel Edit</button>:null}</div>{error?<div style={{color:"#b42318",fontWeight:700}}>{error}</div>:null}{message?<div style={{color:"#18794e",fontWeight:700}}>{message}</div>:null}</form>
      <div style={{marginTop:20,overflowX:"auto",border:"1px solid #e5e9ee",borderRadius:14}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:"#f7f8fa",textAlign:"left"}}>{["Reward","Category","Image","Type","Amount","Fee","Status",""].map(h=><th key={h} style={{padding:"11px 13px",color:"#68717d",fontSize:11,textTransform:"uppercase",letterSpacing:.5}}>{h}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} style={{borderTop:"1px solid #edf0f3",background:"white"}}><td style={{padding:"12px 13px",fontWeight:900}}>{row.display_name}</td><td style={{padding:"12px 13px"}}>{row.category}</td><td style={{padding:"12px 13px"}}>{row.image_url?<div style={{display:"flex",alignItems:"center",gap:8}}><img src={row.image_url} alt="" style={{width:54,height:34,objectFit:"cover",borderRadius:6,border:"1px solid #e2e7ec"}}/><span style={{background:"#eefaf2",color:"#18794e",borderRadius:999,padding:"5px 8px",fontSize:11,fontWeight:800}}>Ready</span></div>:<span style={{background:"#fff4e8",color:"#8a4b12",borderRadius:999,padding:"5px 8px",fontSize:11,fontWeight:800}}>Placeholder</span>}</td><td style={{padding:"12px 13px"}}>{titleCase(row.redemption_type)}</td><td style={{padding:"12px 13px"}}>{row.amount_type==="fixed"?(row.allowed_amounts_cents||[]).map(money).join(", "):"Custom"}</td><td style={{padding:"12px 13px"}}>{row.fee_cents?money(row.fee_cents):"—"}</td><td style={{padding:"12px 13px"}}><span style={{background:row.active?"#eefaf2":"#f0f2f4",color:row.active?"#18794e":"#68717d",borderRadius:999,padding:"5px 8px",fontSize:11,fontWeight:800}}>{row.active?"Active":"Inactive"}</span></td><td style={{padding:"12px 13px"}}><button onClick={()=>edit(row)} style={{border:"1px solid #cfd5dc",borderRadius:8,background:"white",padding:"7px 11px",fontWeight:800,cursor:"pointer"}}>Edit</button></td></tr>)}</tbody></table></div>
    </section></div>
  </main>;
}
