"use client";

import { FormEvent, useEffect, useState } from "react";

type Partner={id:string;name:string;slug:string;status:string;reward_mode:string;reward_basis:string;partner_reward_cents:number;partner_reward_percent:number;guest_discount_cents:number;guest_discount_percent:number;promo_code:string|null;attribution_window_days:number;show_promo_popup:boolean};
type User={id:string;partner_id:string;user_id:string|null;display_name:string;email:string;role:string;active:boolean;invited_at:string|null;last_login_at:string|null};
const field:React.CSSProperties={width:"100%",height:42,border:"1px solid #cfd5dc",borderRadius:10,padding:"0 11px",boxSizing:"border-box",background:"white"};
const label:React.CSSProperties={display:"grid",gap:6,fontSize:12,fontWeight:800,color:"#39414b"};
const card:React.CSSProperties={background:"rgba(255,255,255,.97)",border:"1px solid #dfe4ea",borderRadius:18,boxShadow:"0 14px 34px rgba(26,35,48,.07)"};
const date=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"—";
function Header(){return <header style={{position:"relative",overflow:"hidden",background:"linear-gradient(135deg,#1e2a39 0%,#182230 55%,#111821 100%)",color:"white",padding:"18px 28px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,boxShadow:"0 12px 30px rgba(16,24,33,.18)"}}><div style={{position:"absolute",inset:0,opacity:.1,backgroundImage:"radial-gradient(circle at 20% 20%,#fff 1px,transparent 1px)",backgroundSize:"24px 24px"}}/><div style={{position:"relative",display:"flex",alignItems:"center",gap:18}}><img src="/epic-logo.png" alt="Epic 4X4" style={{width:132,filter:"brightness(0) invert(1)"}}/><div><div style={{fontSize:24,fontWeight:900}}>Ambassador Administration</div><div style={{fontSize:13,opacity:.72}}>Epic 4X4 Adventures</div></div></div><nav style={{position:"relative",display:"flex",gap:8}}>{[["Ambassadors","/ambassador/admin"],["Partner Management","/ambassador/admin/partners"],["Redemptions","/ambassador/admin/redemptions"],["Rewards Catalog","/ambassador/admin/rewards"]].map(([l,h])=><button key={h} onClick={()=>window.location.href=h} style={{border:l==="Partner Management"?0:"1px solid rgba(255,255,255,.28)",background:l==="Partner Management"?"#d5521d":"rgba(255,255,255,.06)",color:"white",borderRadius:10,padding:"10px 14px",fontWeight:l==="Partner Management"?900:800,cursor:"pointer"}}>{l}</button>)}</nav></header>}

export default function PartnerManagement(){
 const [partners,setPartners]=useState<Partner[]>([]);const [selected,setSelected]=useState("");const [users,setUsers]=useState<User[]>([]);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const [name,setName]=useState("");const [slug,setSlug]=useState("");const [contactName,setContactName]=useState("");const [contactEmail,setContactEmail]=useState("");const [mode,setMode]=useState("partner_reward");const [basis,setBasis]=useState("flat");const [partnerReward,setPartnerReward]=useState("25");const [guestDiscount,setGuestDiscount]=useState("0");const [promo,setPromo]=useState("");const [windowDays,setWindowDays]=useState("30");const [popup,setPopup]=useState(false);
 const [uName,setUName]=useState("");const [uEmail,setUEmail]=useState("");const [uRole,setURole]=useState("manager");
 async function loadPartners(){const r=await fetch("/api/ambassador/admin/partner-management",{cache:"no-store"});if(r.status===401||r.status===403){window.location.href="/ambassador/admin/login";return;}const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load Ambassadors.");setPartners(p.partners||[]);if(!selected&&p.partners?.[0])setSelected(p.partners[0].id);}
 async function loadUsers(id:string){if(!id){setUsers([]);return;}const r=await fetch(`/api/ambassador/admin/portal-users?partner_id=${encodeURIComponent(id)}`,{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to load portal users.");setUsers(p.users||[]);}
 useEffect(()=>{loadPartners().catch(e=>setError(e.message));},[]);useEffect(()=>{if(selected)loadUsers(selected).catch(e=>setError(e.message));},[selected]);
 async function createPartner(e:FormEvent){e.preventDefault();setError("");setMessage("");const pv=Number(partnerReward)||0,gv=Number(guestDiscount)||0;const r=await fetch("/api/ambassador/admin/partner-management",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,slug,contact_name:contactName,contact_email:contactEmail,reward_mode:mode,reward_basis:basis,partner_reward_cents:basis==="flat"?Math.round(pv*100):0,partner_reward_percent:basis==="percent"?pv:0,guest_discount_cents:basis==="flat"?Math.round(gv*100):0,guest_discount_percent:basis==="percent"?gv:0,promo_code:promo,attribution_window_days:Number(windowDays)||30,show_promo_popup:popup})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to create Ambassador.");return;}setMessage(`${name} created.`);setName("");setSlug("");setContactName("");setContactEmail("");await loadPartners();}
 async function invite(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/ambassador/admin/portal-users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({partner_id:selected,display_name:uName,email:uEmail,role:uRole})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to invite portal user.");return;}setMessage(`Invitation sent to ${uEmail}.`);setUName("");setUEmail("");await loadUsers(selected);}
 async function access(user:User,active:boolean){const r=await fetch("/api/ambassador/admin/portal-users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({profile_id:user.id,active})});const p=await r.json();if(!r.ok){setError(p.error||"Unable to update access.");return;}await loadUsers(selected);}
 return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 85% 0%,rgba(213,82,29,.10),transparent 28%),linear-gradient(180deg,#f5f7f9 0%,#edf1f4 100%)",fontFamily:"Arial,sans-serif",color:"#202733"}}><Header/><div style={{padding:28,display:"grid",gap:22}}>
  <section style={{...card,padding:24}}><div style={{fontSize:11,fontWeight:900,color:"#d5521d",textTransform:"uppercase",letterSpacing:1}}>Ambassador Setup</div><h1 style={{margin:"4px 0 18px",fontSize:30}}>Add New Ambassador</h1><form onSubmit={createPartner} style={{display:"grid",gap:14}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}><label style={label}>Partner Name<input style={field} value={name} onChange={e=>{setName(e.target.value);if(!slug)setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,""));}} required/></label><label style={label}>Referral Code<input style={field} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())} required/></label><label style={label}>Contact Name<input style={field} value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label style={label}>Contact Email<input style={field} type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label></div><div style={{display:"grid",gridTemplateColumns:"repeat(6,1fr)",gap:12}}><label style={label}>Reward Arrangement<select style={field} value={mode} onChange={e=>setMode(e.target.value)}><option value="partner_reward">Partner Reward</option><option value="guest_discount">Guest Discount</option><option value="split">Split Reward</option></select></label><label style={label}>Calculation<select style={field} value={basis} onChange={e=>setBasis(e.target.value)}><option value="flat">Flat Amount</option><option value="percent">Percentage</option></select></label><label style={label}>Partner Reward<input style={field} type="number" value={partnerReward} onChange={e=>setPartnerReward(e.target.value)}/></label><label style={label}>Guest Discount<input style={field} type="number" value={guestDiscount} onChange={e=>setGuestDiscount(e.target.value)}/></label><label style={label}>Attribution Days<input style={field} type="number" value={windowDays} onChange={e=>setWindowDays(e.target.value)}/></label><label style={label}>TripWorks Promo<input style={field} value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())}/></label></div><label style={{fontSize:13,fontWeight:800,display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={popup} onChange={e=>setPopup(e.target.checked)}/> Show guest promo popup</label><button style={{width:"fit-content",border:0,borderRadius:10,background:"#202733",color:"white",padding:"11px 18px",fontWeight:900}}>Create Ambassador</button></form></section>
  <section style={{...card,padding:24}}><div style={{fontSize:11,fontWeight:900,color:"#d5521d",textTransform:"uppercase",letterSpacing:1}}>Portal Access</div><h2 style={{margin:"4px 0 16px",fontSize:24}}>Invite & Manage Portal Users</h2><form onSubmit={invite} style={{display:"grid",gridTemplateColumns:"1.2fr 1fr 1.2fr .7fr auto",gap:12,alignItems:"end"}}><label style={label}>Ambassador<select style={field} value={selected} onChange={e=>setSelected(e.target.value)}>{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label style={label}>Name<input style={field} value={uName} onChange={e=>setUName(e.target.value)} required/></label><label style={label}>Email<input style={field} type="email" value={uEmail} onChange={e=>setUEmail(e.target.value)} required/></label><label style={label}>Role<select style={field} value={uRole} onChange={e=>setURole(e.target.value)}><option value="owner">Owner</option><option value="manager">Manager</option><option value="viewer">Viewer</option></select></label><button style={{height:42,border:0,borderRadius:10,background:"#d5521d",color:"white",fontWeight:900,padding:"0 16px"}}>Send Invite</button></form>{message?<p style={{color:"#18794e",fontWeight:700}}>{message}</p>:null}{error?<p style={{color:"#b42318",fontWeight:700}}>{error}</p>:null}<div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:"#f7f8fa",textAlign:"left"}}>{["Name","Email","Role","Status","Invited","Last Login","Access"].map(h=><th key={h} style={{padding:"10px 12px",color:"#68717d"}}>{h}</th>)}</tr></thead><tbody>{users.map(u=><tr key={u.id} style={{borderTop:"1px solid #edf0f3"}}><td style={{padding:"11px 12px",fontWeight:800}}>{u.display_name}</td><td style={{padding:"11px 12px"}}>{u.email}</td><td style={{padding:"11px 12px",textTransform:"capitalize"}}>{u.role}</td><td style={{padding:"11px 12px",fontWeight:800}}>{!u.active?"Revoked":u.user_id?"Active":"Invited"}</td><td style={{padding:"11px 12px"}}>{date(u.invited_at)}</td><td style={{padding:"11px 12px"}}>{date(u.last_login_at)}</td><td style={{padding:"11px 12px"}}><button onClick={()=>access(u,!u.active)} style={{border:0,borderRadius:8,padding:"8px 11px",background:u.active?"#fff0f0":"#eefaf2",color:u.active?"#a52323":"#18794e",fontWeight:800}}>{u.active?"Revoke Access":"Reactivate"}</button></td></tr>)}</tbody></table></div></section>
 </div></main>;
}
