"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Adjustment = { id:string; amount_cents:number; adjustment_type:string; reason:string; reference:string|null; created_by_name:string; created_at:string };
type Booking = { id:string; confirmation_code:string|null; customer_name:string|null; experience_name:string|null; activity_start_at:string|null; partner_reward_cents:number; reward_status:string; booking_status:string };
type Partner = { id:string; name:string; slug:string; status:string; reward_mode:string; reward_basis:string; partner_reward_cents:number; partner_reward_percent:number; guest_discount_cents:number; guest_discount_percent:number; earned_cents:number; adjustment_total_cents:number; committed_cents:number; available_cents:number; adjustments:Adjustment[]; recent_bookings:Booking[] };
type Payload = { admin:{display_name:string;role:string}; partners:Partner[] };

const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
const date=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"—";
const card:React.CSSProperties={background:"rgba(255,255,255,.96)",border:"1px solid #dfe4ea",borderRadius:18,boxShadow:"0 14px 34px rgba(26,35,48,.07)"};

export default function AmbassadorAdminPage(){
  const [data,setData]=useState<Payload|null>(null); const [selectedId,setSelectedId]=useState(""); const [amount,setAmount]=useState(""); const [type,setType]=useState("legacy_getambassador"); const [reason,setReason]=useState(""); const [reference,setReference]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){ const r=await fetch("/api/ambassador/admin/partners",{cache:"no-store"}); if(r.status===401||r.status===403){window.location.href="/ambassador/admin/login";return;} const p=await r.json(); if(!r.ok) throw new Error(p.error||"Unable to load administration."); setData(p); if(!selectedId&&p.partners?.[0]) setSelectedId(p.partners[0].id); }
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Unable to load administration."));},[]);
  const selected=useMemo(()=>data?.partners.find(p=>p.id===selectedId)||null,[data,selectedId]);
  async function submit(e:FormEvent){e.preventDefault(); if(!selected) return; setBusy(true); setError(""); setMessage(""); try{const cents=Math.round(Number(amount)*100);const r=await fetch("/api/ambassador/admin/partners",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({partner_id:selected.id,amount_cents:cents,adjustment_type:type,reason,reference})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to save adjustment.");setMessage(`${money(cents)} adjustment added to ${selected.name}.`);setAmount("");setReason("");setReference("");await load();}catch(err){setError(err instanceof Error?err.message:"Unable to save adjustment.");}finally{setBusy(false);}}
  if(!data)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#eef2f5",color:"#68717d",fontFamily:"Arial,sans-serif"}}>{error||"Loading Ambassador administration…"}</main>;
  return <main style={{minHeight:"100vh",background:"radial-gradient(circle at 85% 0%,rgba(213,82,29,.10),transparent 28%),linear-gradient(180deg,#f5f7f9 0%,#edf1f4 100%)",color:"#202733",fontFamily:"Arial,sans-serif"}}>
    <header style={{position:"relative",overflow:"hidden",background:"linear-gradient(135deg,#1e2a39 0%,#182230 55%,#111821 100%)",color:"white",padding:"18px 28px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,boxShadow:"0 12px 30px rgba(16,24,33,.18)"}}>
      <div style={{position:"absolute",inset:0,opacity:.1,backgroundImage:"radial-gradient(circle at 20% 20%,#fff 1px,transparent 1px)",backgroundSize:"24px 24px"}}/>
      <div style={{position:"relative",display:"flex",alignItems:"center",gap:18}}><img src="/epic-logo.png" alt="Epic 4X4" style={{width:132,filter:"brightness(0) invert(1)"}}/><div><div style={{fontSize:24,fontWeight:900}}>Ambassador Administration</div><div style={{fontSize:13,opacity:.72}}>Epic 4X4 Adventures</div></div></div>
      <div style={{position:"relative",fontSize:13,textAlign:"right"}}>{data.admin.display_name}<br/><span style={{opacity:.72,textTransform:"capitalize"}}>{data.admin.role}</span></div>
    </header>
    <div style={{padding:28,display:"grid",gridTemplateColumns:"320px minmax(0,1fr)",gap:24}}>
      <aside style={{...card,padding:18,height:"fit-content",position:"sticky",top:70}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><h2 style={{margin:0,fontSize:19}}>Ambassadors</h2><span style={{fontSize:11,fontWeight:900,color:"#d5521d",background:"#fff2eb",padding:"5px 8px",borderRadius:999}}>{data.partners.length}</span></div><div style={{display:"grid",gap:9}}>{data.partners.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} style={{textAlign:"left",border:selectedId===p.id?"2px solid #d5521d":"1px solid #e2e7ec",background:selectedId===p.id?"linear-gradient(135deg,#fff7f2,#fff)":"white",borderRadius:12,padding:"12px 13px",cursor:"pointer",boxShadow:selectedId===p.id?"0 10px 24px rgba(213,82,29,.10)":"none"}}><strong>{p.name}</strong><div style={{fontSize:12,color:"#68717d",marginTop:4}}>{p.slug} · {p.status}</div><div style={{fontSize:12,marginTop:7}}>Available: <strong>{money(p.available_cents)}</strong></div></button>)}</div></aside>
      {selected?<section style={{display:"grid",gap:20}}>
        <div style={{...card,padding:24}}><div style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start"}}><div><div style={{fontSize:11,fontWeight:900,color:"#d5521d",textTransform:"uppercase",letterSpacing:1}}>Partner Account</div><h1 style={{margin:"4px 0 0",fontSize:30}}>{selected.name}</h1><p style={{margin:"6px 0 0",color:"#68717d"}}>Referral code: <strong style={{color:"#202733"}}>{selected.slug}</strong></p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>window.open(`/ambassador/admin/portal/${encodeURIComponent(selected.id)}`,"_blank")} style={{border:0,borderRadius:10,background:"#202733",color:"white",padding:"11px 15px",fontWeight:900,cursor:"pointer",boxShadow:"0 10px 24px rgba(32,39,51,.18)"}}>View Portal</button><button onClick={()=>navigator.clipboard.writeText(`https://www.epic4x4adventures.com/?ref=${selected.slug}`)} style={{border:"1px solid #cfd6de",borderRadius:10,background:"white",padding:"11px 15px",fontWeight:800,cursor:"pointer"}}>Copy Referral Link</button></div></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:14,marginTop:20}}>{[["Earned + Adjustments",selected.earned_cents],["Manual Adjustments",selected.adjustment_total_cents],["In Redemption",selected.committed_cents],["Available",selected.available_cents]].map(([l,v],i)=><div key={String(l)} style={{background:i===3?"linear-gradient(135deg,#fff1ea,#fff)":"#f7f8fa",border:i===3?"1px solid #f4c2aa":"1px solid #edf0f3",borderRadius:14,padding:16}}><div style={{fontSize:11,color:"#68717d",fontWeight:900,textTransform:"uppercase",letterSpacing:.5}}>{l}</div><div style={{fontSize:26,fontWeight:900,marginTop:6,color:i===3?"#d5521d":"#202733"}}>{money(Number(v))}</div></div>)}</div></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
          <form onSubmit={submit} style={{...card,padding:24}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:6}}><div style={{width:34,height:34,borderRadius:10,display:"grid",placeItems:"center",background:"#fff1ea",color:"#d5521d",fontWeight:900}}>+</div><h2 style={{margin:0,fontSize:21}}>Manual Reward Adjustment</h2></div><p style={{margin:"0 0 18px",color:"#68717d",fontSize:13,lineHeight:1.5}}>Use this for missing legacy rewards or corrections. Every adjustment is permanently stamped with your Epic employee identity and time.</p>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Adjustment Type<select value={type} onChange={e=>setType(e.target.value)} style={{height:44,border:"1px solid #cfd6de",borderRadius:10,padding:"0 11px",background:"white"}}><option value="legacy_getambassador">Legacy GetAmbassador Reward</option><option value="manual">Manual Reward</option><option value="correction">Correction</option></select></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:13}}>Amount ($)<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" step="0.01" required style={{height:44,border:"1px solid #cfd6de",borderRadius:10,padding:"0 11px"}}/></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:13}}>Reason<input value={reason} onChange={e=>setReason(e.target.value)} required placeholder="Missing rewards after GetAmbassador shutdown" style={{height:44,border:"1px solid #cfd6de",borderRadius:10,padding:"0 11px"}}/></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:13}}>Reference / confirmation IDs (optional)<textarea value={reference} onChange={e=>setReference(e.target.value)} rows={3} style={{border:"1px solid #cfd6de",borderRadius:10,padding:11}}/></label>
            {error?<p style={{color:"#b42318",fontSize:13,fontWeight:700}}>{error}</p>:null}{message?<p style={{color:"#18794e",fontSize:13,fontWeight:700}}>{message}</p>:null}
            <button disabled={busy} type="submit" style={{width:"100%",height:46,marginTop:15,border:0,borderRadius:10,background:"linear-gradient(135deg,#df5b22,#c94716)",color:"white",fontWeight:900,cursor:busy?"wait":"pointer",boxShadow:"0 10px 22px rgba(213,82,29,.20)"}}>{busy?"Saving…":"Add Adjustment"}</button>
          </form>
          <div style={{...card,padding:24}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8}}><div style={{width:34,height:34,borderRadius:10,display:"grid",placeItems:"center",background:"#eef3f7",fontWeight:900}}>↺</div><h2 style={{margin:0,fontSize:21}}>Adjustment History</h2></div>{selected.adjustments.length?selected.adjustments.map(a=><div key={a.id} style={{borderTop:"1px solid #edf0f3",padding:"13px 0"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong style={{color:a.amount_cents>=0?"#18794e":"#b42318",fontSize:16}}>{a.amount_cents>=0?"+":""}{money(a.amount_cents)}</strong><span style={{fontSize:12,color:"#68717d"}}>{date(a.created_at)}</span></div><div style={{marginTop:5,fontSize:13}}>{a.reason}</div><div style={{fontSize:12,color:"#68717d",marginTop:3}}>By {a.created_by_name}{a.reference?` · ${a.reference}`:""}</div></div>):<div style={{marginTop:14,padding:24,border:"1px dashed #d8dee5",borderRadius:12,textAlign:"center",color:"#68717d",fontSize:13}}>No manual adjustments yet.</div>}</div>
        </div>
        <div style={{...card,overflow:"hidden"}}><div style={{padding:"18px 22px",borderBottom:"1px solid #e5e9ee",display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{margin:0,fontSize:20}}>Recent Referral Bookings</h2><span style={{fontSize:12,color:"#68717d"}}>Latest activity for this Ambassador</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:"#f8f9fa",textAlign:"left"}}>{["Confirmation","Guest","Experience","Travel","Reward","Status"].map(h=><th key={h} style={{padding:"11px 13px",color:"#68717d",fontSize:11,textTransform:"uppercase",letterSpacing:.5}}>{h}</th>)}</tr></thead><tbody>{selected.recent_bookings.length?selected.recent_bookings.map(b=><tr key={b.id} style={{borderTop:"1px solid #edf0f3"}}><td style={{padding:"12px 13px",fontWeight:800}}>{b.confirmation_code||"—"}</td><td style={{padding:"12px 13px"}}>{b.customer_name||"—"}</td><td style={{padding:"12px 13px"}}>{b.experience_name||"—"}</td><td style={{padding:"12px 13px"}}>{date(b.activity_start_at)}</td><td style={{padding:"12px 13px",fontWeight:900}}>{money(b.partner_reward_cents)}</td><td style={{padding:"12px 13px"}}><span style={{background:"#eef3f7",borderRadius:999,padding:"5px 8px",fontSize:11,fontWeight:800,textTransform:"capitalize"}}>{b.reward_status}</span></td></tr>):<tr><td colSpan={6} style={{padding:30,textAlign:"center",color:"#68717d"}}>No referral bookings yet.</td></tr>}</tbody></table></div></div>
      </section>:null}
    </div>
  </main>;
}
