"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Adjustment = { id:string; amount_cents:number; adjustment_type:string; reason:string; reference:string|null; created_by_name:string; created_at:string };
type Booking = { id:string; confirmation_code:string|null; customer_name:string|null; experience_name:string|null; activity_start_at:string|null; partner_reward_cents:number; reward_status:string; booking_status:string };
type Partner = { id:string; name:string; slug:string; status:string; reward_mode:string; reward_basis:string; partner_reward_cents:number; partner_reward_percent:number; guest_discount_cents:number; guest_discount_percent:number; earned_cents:number; adjustment_total_cents:number; committed_cents:number; available_cents:number; adjustments:Adjustment[]; recent_bookings:Booking[] };
type Payload = { admin:{display_name:string;role:string}; partners:Partner[] };

const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format((c||0)/100);
const date=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(v)):"—";

export default function AmbassadorAdminPage(){
  const [data,setData]=useState<Payload|null>(null); const [selectedId,setSelectedId]=useState(""); const [amount,setAmount]=useState(""); const [type,setType]=useState("legacy_getambassador"); const [reason,setReason]=useState(""); const [reference,setReference]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function load(){ const r=await fetch("/api/ambassador/admin/partners",{cache:"no-store"}); if(r.status===401||r.status===403){window.location.href="/ambassador/admin/login";return;} const p=await r.json(); if(!r.ok) throw new Error(p.error||"Unable to load administration."); setData(p); if(!selectedId&&p.partners?.[0]) setSelectedId(p.partners[0].id); }
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:"Unable to load administration."));},[]);
  const selected=useMemo(()=>data?.partners.find(p=>p.id===selectedId)||null,[data,selectedId]);
  async function submit(e:FormEvent){e.preventDefault(); if(!selected) return; setBusy(true); setError(""); setMessage(""); try{const cents=Math.round(Number(amount)*100);const r=await fetch("/api/ambassador/admin/partners",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({partner_id:selected.id,amount_cents:cents,adjustment_type:type,reason,reference})});const p=await r.json();if(!r.ok)throw new Error(p.error||"Unable to save adjustment.");setMessage(`${money(cents)} adjustment added to ${selected.name}.`);setAmount("");setReason("");setReference("");await load();}catch(err){setError(err instanceof Error?err.message:"Unable to save adjustment.");}finally{setBusy(false);}}
  if(!data)return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f1f3f5",color:"#68717d"}}>{error||"Loading Ambassador administration…"}</main>;
  return <main style={{minHeight:"100vh",background:"#f1f3f5",color:"#202733",fontFamily:"Arial,sans-serif"}}>
    <header style={{background:"#202733",color:"white",padding:"16px 26px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:20}}>
      <div style={{display:"flex",alignItems:"center",gap:18}}><img src="/epic-logo.png" alt="Epic 4X4" style={{width:130,filter:"brightness(0) invert(1)"}}/><div><div style={{fontSize:22,fontWeight:900}}>Ambassador Administration</div><div style={{fontSize:13,opacity:.72}}>Epic 4X4 Adventures</div></div></div>
      <div style={{display:"flex",alignItems:"center",gap:18}}><nav style={{display:"flex",gap:8}}><button style={{border:0,background:"#d5521d",color:"white",borderRadius:8,padding:"9px 13px",fontWeight:900}}>Ambassadors</button><button onClick={()=>window.location.href="/ambassador/admin/rewards"} style={{border:"1px solid rgba(255,255,255,.28)",background:"transparent",color:"white",borderRadius:8,padding:"9px 13px",fontWeight:800,cursor:"pointer"}}>Rewards Catalog</button></nav><div style={{fontSize:13,textAlign:"right"}}>{data.admin.display_name}<br/><span style={{opacity:.72,textTransform:"capitalize"}}>{data.admin.role}</span></div></div>
    </header>
    <div style={{padding:26,display:"grid",gridTemplateColumns:"310px minmax(0,1fr)",gap:22}}>
      <aside style={{background:"white",border:"1px solid #dfe4ea",borderRadius:14,padding:16,height:"fit-content"}}><h2 style={{margin:"0 0 12px",fontSize:18}}>Ambassadors</h2><div style={{display:"grid",gap:8}}>{data.partners.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} style={{textAlign:"left",border:selectedId===p.id?"2px solid #d5521d":"1px solid #e2e7ec",background:selectedId===p.id?"#fff7f2":"white",borderRadius:9,padding:"11px 12px",cursor:"pointer"}}><strong>{p.name}</strong><div style={{fontSize:12,color:"#68717d",marginTop:3}}>{p.slug} · {p.status}</div><div style={{fontSize:12,marginTop:5}}>Available: <strong>{money(p.available_cents)}</strong></div></button>)}</div></aside>
      {selected?<section style={{display:"grid",gap:18}}>
        <div style={{background:"white",border:"1px solid #dfe4ea",borderRadius:14,padding:22}}><div><h1 style={{margin:0,fontSize:28}}>{selected.name}</h1><p style={{margin:"5px 0 0",color:"#68717d"}}>Referral code: {selected.slug}</p></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12,marginTop:18}}>{[["Earned + Adjustments",selected.earned_cents],["Manual Adjustments",selected.adjustment_total_cents],["In Redemption",selected.committed_cents],["Available",selected.available_cents]].map(([l,v])=><div key={String(l)} style={{background:"#f7f8fa",borderRadius:10,padding:14}}><div style={{fontSize:12,color:"#68717d",fontWeight:700}}>{l}</div><div style={{fontSize:24,fontWeight:900,marginTop:5}}>{money(Number(v))}</div></div>)}</div></div>

        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}>
          <form onSubmit={submit} style={{background:"white",border:"1px solid #dfe4ea",borderRadius:14,padding:22}}><h2 style={{margin:"0 0 6px",fontSize:20}}>Manual Reward Adjustment</h2><p style={{margin:"0 0 16px",color:"#68717d",fontSize:13,lineHeight:1.5}}>Use this for missing legacy rewards or corrections. Every adjustment is permanently stamped with your Epic employee identity and time.</p>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800}}>Adjustment Type<select value={type} onChange={e=>setType(e.target.value)} style={{height:42,border:"1px solid #cfd6de",borderRadius:8,padding:"0 10px"}}><option value="legacy_getambassador">Legacy GetAmbassador Reward</option><option value="manual">Manual Reward</option><option value="correction">Correction</option></select></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:12}}>Amount ($)<input value={amount} onChange={e=>setAmount(e.target.value)} type="number" step="0.01" required style={{height:42,border:"1px solid #cfd6de",borderRadius:8,padding:"0 10px"}}/></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:12}}>Reason<input value={reason} onChange={e=>setReason(e.target.value)} required placeholder="Missing rewards after GetAmbassador shutdown" style={{height:42,border:"1px solid #cfd6de",borderRadius:8,padding:"0 10px"}}/></label>
            <label style={{display:"grid",gap:6,fontSize:12,fontWeight:800,marginTop:12}}>Reference / confirmation IDs (optional)<textarea value={reference} onChange={e=>setReference(e.target.value)} rows={3} style={{border:"1px solid #cfd6de",borderRadius:8,padding:10}}/></label>
            {error?<p style={{color:"#b42318",fontSize:13,fontWeight:700}}>{error}</p>:null}{message?<p style={{color:"#18794e",fontSize:13,fontWeight:700}}>{message}</p>:null}
            <button disabled={busy} type="submit" style={{width:"100%",height:44,marginTop:14,border:0,borderRadius:8,background:"#d5521d",color:"white",fontWeight:900,cursor:busy?"wait":"pointer"}}>{busy?"Saving…":"Add Adjustment"}</button>
          </form>
          <div style={{background:"white",border:"1px solid #dfe4ea",borderRadius:14,padding:22}}><h2 style={{margin:"0 0 12px",fontSize:20}}>Adjustment History</h2>{selected.adjustments.length?selected.adjustments.map(a=><div key={a.id} style={{borderTop:"1px solid #edf0f3",padding:"11px 0"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong style={{color:a.amount_cents>=0?"#18794e":"#b42318"}}>{a.amount_cents>=0?"+":""}{money(a.amount_cents)}</strong><span style={{fontSize:12,color:"#68717d"}}>{date(a.created_at)}</span></div><div style={{marginTop:4,fontSize:13}}>{a.reason}</div><div style={{fontSize:12,color:"#68717d",marginTop:3}}>By {a.created_by_name}{a.reference?` · ${a.reference}`:""}</div></div>):<p style={{color:"#68717d",fontSize:13}}>No manual adjustments yet.</p>}</div>
        </div>

        <div style={{background:"white",border:"1px solid #dfe4ea",borderRadius:14,overflow:"hidden"}}><div style={{padding:"17px 20px",borderBottom:"1px solid #e5e9ee"}}><h2 style={{margin:0,fontSize:19}}>Recent Referral Bookings</h2></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:"#f8f9fa",textAlign:"left"}}>{["Confirmation","Guest","Experience","Travel","Reward","Status"].map(h=><th key={h} style={{padding:"10px 12px",color:"#68717d"}}>{h}</th>)}</tr></thead><tbody>{selected.recent_bookings.length?selected.recent_bookings.map(b=><tr key={b.id} style={{borderTop:"1px solid #edf0f3"}}><td style={{padding:"11px 12px",fontWeight:800}}>{b.confirmation_code||"—"}</td><td style={{padding:"11px 12px"}}>{b.customer_name||"—"}</td><td style={{padding:"11px 12px"}}>{b.experience_name||"—"}</td><td style={{padding:"11px 12px"}}>{date(b.activity_start_at)}</td><td style={{padding:"11px 12px",fontWeight:800}}>{money(b.partner_reward_cents)}</td><td style={{padding:"11px 12px"}}>{b.reward_status}</td></tr>):<tr><td colSpan={6} style={{padding:26,textAlign:"center",color:"#68717d"}}>No referral bookings yet.</td></tr>}</tbody></table></div></div>
      </section>:null}
    </div>
  </main>;
}
