"use client";
import {useEffect,useState} from "react";
type Ping={id:string;from_id:string;to_id:string;from_name:string;to_name:string;body:string;at:string;status:string|null;responded_at:string|null};
type Member={id:string;name:string};
export default function EpicPing(){
const [data,setData]=useState<{profile:{id:string;name:string};members:Member[];messages:Ping[]}|null>(null);
const [recipient,setRecipient]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
async function load(){try{const r=await fetch("/api/team/epic-ping",{cache:"no-store"});const p=await r.json();if(!r.ok)throw Error(p.error||"Unable to load");setData(p);}catch(e){setError(e instanceof Error?e.message:"Unable to load");}}
useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load()},10000);return()=>clearInterval(timer)},[]);
async function act(payload:object){setBusy(true);setError("");try{const r=await fetch("/api/team/epic-ping",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.error||"Action failed");setMessage("");await load();}catch(e){setError(e instanceof Error?e.message:"Action failed")}finally{setBusy(false)}}
const unread=(data?.messages||[]).filter(p=>p.to_id===data?.profile.id&&!p.status).length;
return <div style={{padding:24,maxWidth:850,margin:"auto",display:"grid",gap:16}}><h1>Epic Ping {unread>0?<span style={{color:"#c6472b"}}>· {unread} waiting</span>:null}</h1><p>Quick internal messages between Epic employees, independent of any customer or reservation.</p>
<section style={{padding:18,border:"1px solid #dce2e8",borderRadius:12,display:"grid",gap:12,background:"white"}}><strong>New Ping</strong><select value={recipient} onChange={e=>setRecipient(e.target.value)} style={{padding:10}}><option value="">Choose colleague…</option>{(data?.members||[]).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="What would you like to tell them?" style={{padding:10}}/><button type="button" disabled={!recipient||!message.trim()||busy} onClick={()=>void act({action:"send",recipient,message})}>Send Ping</button></section>
<h2>Conversations</h2>{(data?.messages||[]).map(p=><article key={p.id} style={{padding:14,border:"1px solid #dce2e8",background:"white",borderRadius:12,display:"grid",gap:8}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>{p.from_name} → {p.to_name}</strong><small>{new Date(p.at).toLocaleString()}</small></div><div style={{whiteSpace:"pre-wrap"}}>{p.body}</div><small>{p.status||"Waiting for acknowledgment"}{p.responded_at?" · "+new Date(p.responded_at).toLocaleString():""}</small><div style={{display:"flex",gap:8}}>{p.to_id===data?.profile.id&&!p.status?<><button type="button" disabled={busy} onClick={()=>void act({action:"acknowledged",id:p.id})}>Acknowledge</button><button type="button" disabled={busy} onClick={()=>void act({action:"dismissed",id:p.id})}>Dismiss</button></>:null}<button type="button" onClick={()=>{setRecipient(p.from_id===data?.profile.id?p.to_id:p.from_id);setMessage("Re: "+p.body.slice(0,100)+"\n");window.scrollTo({top:0,behavior:"smooth"});}}>Reply</button></div></article>)}{error?<div role="alert" style={{color:"#ad2626"}}>{error}</div>:null}</div>;
}
