import { NextRequest, NextResponse } from "next/server";
import { getAuthenticatedAmbassadorAdmin } from "@/lib/ambassador-admin-auth";

function cfg(){const raw=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();const key=process.env.SUPABASE_SECRET_KEY?.trim();if(!raw||!key)throw new Error("Supabase server environment variables are missing.");return{url:(/^https?:\/\//i.test(raw)?raw:`https://${raw}`).replace(/\/+$/,"") ,key};}
async function rest<T>(path:string,init?:RequestInit):Promise<T>{const{url,key}=cfg();const r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const text=await r.text();if(!r.ok)throw new Error(text||`Supabase request failed (${r.status}).`);return text?JSON.parse(text) as T:undefined as T;}
async function admin(req:NextRequest){return getAuthenticatedAmbassadorAdmin(req.cookies.get("epic_ambassador_admin_access_token")?.value);}

export async function GET(req:NextRequest){if(!await admin(req))return NextResponse.json({error:"Ambassador administrator access required."},{status:403});try{const rows=await rest<any[]>(`referral_redemptions?select=${encodeURIComponent("id,partner_id,amount_cents,method,method_details,status,requested_at,approved_at,sent_at,completed_at,rejected_at,cancelled_at,provider,provider_reference,internal_notes")}&order=requested_at.desc&limit=200`);const partnerIds=[...new Set(rows.map(r=>r.partner_id).filter(Boolean))];const partners=partnerIds.length?await rest<any[]>(`referral_partners?id=in.(${partnerIds.join(",")})&select=id,name,slug`):[];const map=new Map(partners.map(p=>[p.id,p]));return NextResponse.json({ok:true,redemptions:rows.map(r=>({...r,partner:map.get(r.partner_id)||null}))});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load redemption requests."},{status:500});}}

export async function PATCH(req:NextRequest){if(!await admin(req))return NextResponse.json({error:"Ambassador administrator access required."},{status:403});const body=await req.json().catch(()=>null) as Record<string,unknown>|null;const id=typeof body?.id==="string"?body.id:"";const status=typeof body?.status==="string"?body.status:"";if(!id||!["approved","sent","completed","rejected","cancelled"].includes(status))return NextResponse.json({error:"Valid redemption and status are required."},{status:400});const now=new Date().toISOString();const patch:Record<string,unknown>={status,updated_at:now};if(status==="approved")patch.approved_at=now;if(status==="sent")patch.sent_at=now;if(status==="completed")patch.completed_at=now;if(status==="rejected")patch.rejected_at=now;if(status==="cancelled")patch.cancelled_at=now;if(typeof body?.provider==="string")patch.provider=body.provider.trim()||null;if(typeof body?.provider_reference==="string")patch.provider_reference=body.provider_reference.trim()||null;if(typeof body?.internal_notes==="string")patch.internal_notes=body.internal_notes.trim()||null;try{await rest<void>(`referral_redemptions?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify(patch)});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to update redemption request."},{status:500});}}
